version: '3'
services:
  backend:
    build:
      context: ./NOBUZZ-TEST-backend
    ports:
      - "8181:8181"
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=nobuzztest
      - DATABASE_PASSWORD=nobuzztest
      - DATABASE_NAME=nobuzztest

    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql


  frontend:
    build:
      context: ./nobuzz_test_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: nobuzztest
      POSTGRES_PASSWORD: nobuzztest
      POSTGRES_DB: nobuzztest
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
